### ISSUE TITLE
Borders throws error

### ISSUE THREAD

**Issue by krisrs1128** [krisrs1128/glacier_mapping#12]
If you ask for `borders: true` in the config, we get the error below (we have discussed this before). I don't think we really need to be using borders, but we should print a more informative error message.

```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kris/glacier_mapping/src/exper.py", line 80, in <module>
    trainer.train()
  File "/home/kris/glacier_mapping/src/trainer.py", line 34, in train
    self.train_epoch(op, loss_f)
  File "/home/kris/glacier_mapping/src/trainer.py", line 53, in train_epoch
    for i, (img, mask) in enumerate(self.train_data):
  File "/home/kris/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/kris/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/kris/.local/lib/python3.6/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/kris/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kris/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kris/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/kris/glacier_mapping/src/dataset.py", line 71, in __getitem__
    img = self.img_transform(img)
  File "/home/kris/.local/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 175, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "/home/kris/.local/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 217, in normalize
    tensor.sub_(mean[:, None, None]).div_(std[:, None, None])
RuntimeError: The size of tensor a (7) must match the size of tensor b (6) at non-singleton dimension 0
```

**Comment by Sh-imaa** [comment]
Resolved in https://github.com/Sh-imaa/glacier_mapping/pull/13
